Update dask_cudf api for multi_gpu_pagerank.ipynb
there is an AttributeError: 'DataFrame' object has no attribute 'store_transposed' that still needs to be resolved by the cugraph team